linters:
  disable-all: true
  enable:
    - gofmt
    - govet

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
