linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
  
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
